import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Welcome from "@/components/Welcome";
import User from "@/components/User";
import Description from "@/components/Description";
import Pet from "@/components/Pet"
import Counter from "@/components/Counter";
import UserForm from "@/components/UserForm";
import Tasklist from "@/components/Tasklist";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1> Hello World! </h1>
        <Welcome/>
        <hr></hr>
        <User/>
        <Description city="Registro" age ={18} email ="larissa@email.com"/>
        <Pet name="Nina" breed="Vira lata" age = {12} />
        <Counter/>
        <UserForm/>
        <Tasklist/>
      </main>
    </>
  );
}
